name: "Parser: Test and Lint Parser"

on:
  push:
    paths:
    - 'mlh_parser/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  parser-tests:
    uses: ./.github/workflows/rust-tests.yaml
    name: parser-tests
    with:
      path: ./mlh_parser
      project-name: mlh_parser

  parser-lint:
    uses: ./.github/workflows/rust-lint.yaml
    name: parser-lint
    with:
      path: ./mlh_parser
      project-name: mlh_parser
