name: Parser Test

on:
  pull_request:
      paths:
      - 'mlh_parser/**'
  workflow_dispatch:

jobs:
  parser-tests:
    uses: ./.github/workflows/py-tests.yaml
    name: parser-tests
    with:
      path: ./mlh_parser

