name: Python Test

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      project-name:
        required: true
        type: string

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.14"

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install NOX
        run: uv tool install nox

      - name: Install the project
        run: cd ${{ inputs.path }}  && uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: cd ${{ inputs.path }} && uv tool run nox -s tests

      - name: Upload coverage XML
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ inputs.project-name }}-py${{ matrix.python-version }}
          path: ${{ inputs.path }}/coverage.xml
          if-no-files-found: ignore

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html-${{ inputs.project-name }}-py${{ matrix.python-version }}
          path: ${{ inputs.path }}/htmlcov/
          if-no-files-found: ignore
          retention-days: 7
