name: Check for Typos

on:
  workflow_dispatch:
  push:

jobs:
  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@v1
        with:
          write_changes: true
